import bpy
import math
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete()
# 사다리 만들기
# 사다리대 (왼쪽)
bpy.ops.mesh.primitive_cube_add(location=(0, 0, 0))
bpy.context.object.scale = (0.2, 2, 0.2)
# 사다리대 (오른쪽)
bpy.ops.mesh.primitive_cube_add(location=(1.2, 0, 0))
bpy.context.object.scale = (0.2, 2, 0.2)
# 사다리판 (1단)
bpy.ops.mesh.primitive_cube_add(location=(0.6, 0, 0.2))
bpy.context.object.scale = (1, 0.2, 0.2)
# 사다리판 (2단)
bpy.ops.mesh.primitive_cube_add(location=(0.6, 0, 0.4))
bpy.context.object.scale = (1, 0.2, 0.2)
# 사다리판 (3단)
bpy.ops.mesh.primitive_cube_add(location=(0.6, 0, 0.6))
bpy.context.object.scale = (1, 0.2, 0.2)
# 사다리판 (4단)
bpy.ops.mesh.primitive_cube_add(location=(0.6, 0, 0.8))
bpy.context.object.scale = (1, 0.2, 0.2)
# 사다리판 (5단)
bpy.ops.mesh.primitive_cube_add(location=(0.6, 0, 1.0))
bpy.context.object.scale = (1, 0.2, 0.2)
# 사다리판 (6단)
bpy.ops.mesh.primitive_cube_add(location=(0.6, 0, 1.2))
bpy.context.object.scale = (1, 0.2, 0.2)
# 사다리판 (7단)
bpy.ops.mesh.primitive_cube_add(location=(0.6, 0, 1.4))
bpy.context.object.scale = (1, 0.2, 0.2)
# 사다리판 (8단)
bpy.ops.mesh.primitive_cube_add(location=(0.6, 0, 1.6))
bpy.context.object.scale = (1, 0.2, 0.2)
# 사다리판 (9단)
bpy.ops.mesh.primitive_cube_add(location=(0.6, 0, 1.8))
bpy.context.object.scale = (1, 0.2, 0.2)
# 사다리판 (10단)
bpy.ops.mesh.primitive_cube_add(location=(0.6, 0, 2.0))
bpy.context.object.scale = (1, 0.2, 0.2)